name:                tp-stocks
version:             0.1.0.0
github:              "bartavelle/tp-stocks"
license:             BSD3
author:              "Simon Marechal"
maintainer:          "bartavelle@banquise.net"
copyright:           "Simon Marechal"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/bartavelle/tp-stocks#readme>

dependencies:
- base >= 4.7 && < 5
- containers

library:
  source-dirs: src
  ghc-options:
  - -Wall

executables:
  tp-stocks-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -Wall
    dependencies:
    - tp-stocks

tests:
  tp-stocks-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -Wall
    dependencies:
    - tp-stocks
    - hspec
